export const LOGIN_START = 'LOGIN_START'
export const LOGIN_OK = 'LOGIN_OK'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const GET_DATA_START = 'GET_DATA_START'
export const GET_DATA_OK = 'GET_DATA_OK'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'

export const FETCH_CURRENT_STATE_START = 'FETCH_CURRENT_STATE_START';
export const FETCH_CURRENT_STATE_OK = 'FETCH_CURRENT_STATE_OK';
export const FETCH_CURRENT_STATE_ERROR = 'FETCH_CURRENT_STATE_ERROR';