import os

BUILD_DIR = "./build"
SRC_DIR = "./src"
INSTALL_DIR = "./install"
INCLUDE_DIR = "./include"
BINARY_NAME = "zpr"

# create object files in BUILD_DIR directory
VariantDir(BUILD_DIR, SRC_DIR, duplicate=0)
env = Environment(TARGET_ARCH='x86', CCFLAGS=["-fPIC", "-Wall"])

# collect files for compilation
sources = Glob(BUILD_DIR + '/*.cpp')
if len(sources) == 0:
    print("No files given!")
    exit(1)

env.Append(CPPPATH= [
    "libs/boost/
])